name: kubetest2 release

on:
  workflow_dispatch:
  schedule:
    - cron: '* 0 * * 1'

permissions:
  contents: read

env:
  ARTIFACT: oci://ghcr.io/${{github.repository_owner}}/kubetest2-aks

jobs:
  build-kubetest2-aks:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: master
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: kubetest2-aks/go.mod
      - name: Build binary
        run: |
          cd kubetest2-aks
          make deployer
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup kustomizer
        uses: stefanprodan/kustomizer/action@d5f7cea0a21fd41c44c6a0b808a436b9a66fa8d6 # main
      - name: Push
        run: |
          kustomizer push artifact ${ARTIFACT}:${{ github.ref_name }} -f ./kubetest2-aks/bin/kubetest2-aks \
            --source=${{ github.repositoryUrl }} \
            --revision="${{ github.ref_name }}/${{ github.sha }}"
      - name: Tag latest
        run: |
          kustomizer tag artifact ${ARTIFACT}:${GITHUB_REF_NAME} latest