name: Trivy scanner

on:
  workflow_dispatch:
  push:
    branches: [ master, 'release-**' ]
    paths:
      - '.github/workflows/trivy.yaml'
      - 'pkg/**.go'
      - '!pkg/azureclients/v2/**.go'
      - '!kubetest2-aks/**.go'
      - 'cmd/**.go'
      - 'go.*'
      - '!vendor/**'
      - 'health-probe-proxy/**'
  pull_request:
    branches: [ master, 'release-**' ]
    paths:
      - '.github/workflows/trivy.yaml'
      - 'pkg/**.go'
      - '!pkg/azureclients/v2/**.go'
      - '!kubetest2-aks/**.go'
      - 'cmd/**.go'
      - 'go.*'
      - '!vendor/**'
      - 'health-probe-proxy/**'
  schedule:
    - cron: '35 12 * * 4'
permissions:
  contents: read
jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Set up Go 1.x
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '>=1.20'
          check-latest: true
        id: go
      - name: Build images
        run: |
          export TAG=${{ github.sha }}
          export IMAGE_TAG=${{ github.sha }}
          make build-ccm-image
          make build-node-image-linux-amd64
          cd health-probe-proxy && make build-health-probe-proxy-image && cd ..

      - name: Run Trivy scanner CCM
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # master
        with:
          image-ref: 'local/azure-cloud-controller-manager:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-ccm-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3.25.11
        with:
          sarif_file: 'trivy-ccm-results.sarif'
          category: azure-cloud-controller-manager-image
      - name: Run Trivy scanner CNM
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # master
        with:
          image-ref: 'local/azure-cloud-node-manager:${{ github.sha }}-linux-amd64'
          format: 'sarif'
          output: 'trivy-cnm-linux-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3.25.11
        with:
          sarif_file: 'trivy-cnm-linux-results.sarif'
          category: azure-cloud-node-manager-linux-image
      - name: Run Trivy scanner health-probe-proxy
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # master
        with:
          image-ref: 'local/health-probe-proxy:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-health-probe-proxy-linux-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3.25.11
        with:
          sarif_file: 'trivy-health-probe-proxy-linux-results.sarif'
          category: health-probe-proxy-linux-image

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
